name: Daily AI Post

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"  # runs daily at 9 AM UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Generate post
        run: python scripts/generate_post.py

      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Add new daily AI post" || echo "No changes to commit"
          git push
