name: Daily AI Post

on:
  schedule:
    - cron: "0 9 * * *"   # každý deň o 09:00 UTC
  workflow_dispatch:       # manuálne spustenie

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Generate new post
        run: python scripts/generate_post.py

      - name: Update index
        run: python scripts/update_index.py

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Add new daily AI post" || echo "No changes"
          git push
