name: Generate Daily Post

on:
  schedule:
    - cron: "0 8 * * *"   # každý deň o 08:00 UTC
  workflow_dispatch:       # ručný štart

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PIXABAY_API_KEY: ${{ secrets.PIXABAY_API_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Generate JSON post (800+ slov + obrázok)
        run: python scripts/generate_post.py

      - name: Build HTML pages from JSON
        run: python scripts/generate_pages.py

      - name: Update index.html
        run: python scripts/update_index.py

      - name: Commit & push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add index.html posts/*.json posts/*.html images/*
          git commit -m "Daily auto-post + pages + index" || echo "No changes to commit"
          git push
