name: Generate and Deploy Post

on:
  schedule:
    - cron: "0 8 * * *"  # každý deň o 08:00 ráno
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate post
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python scripts/generate_post.py

      - name: Update index.html
        run: |
          python scripts/update_index.py

      - name: Generate post pages
        run: |
          python scripts/generate_pages.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Add new post" || echo "No changes to commit"
          git push
