name: Generate Daily Blog Post

on:
  schedule:
    - cron: "0 8 * * *"   # každý deň o 08:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests pyyaml

      - name: Generate new post
        run: python scripts/generate_post.py

      - name: Update index and HTML pages
        run: python scripts/update_index.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add posts/ static/ index.html
          git commit -m "Generated new post"
          git push
