name: Generate Blog Post

on:
  schedule:
    - cron: "0 8 * * *"   # každý deň o 08:00
  workflow_dispatch:       # možnosť spustiť manuálne

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Generate new blog post
        run: python scripts/generate_post.py
        env:
          PIXABAY_API_KEY: ${{ secrets.PIXABAY_API_KEY }}

      - name: Update index.html
        run: python scripts/update_index.py

      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add .
          git commit -m "📄 New blog post generated on $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push
