name: Daily Post

on:
  schedule:
    - cron: "0 9 * * *"  # Runs daily at 09:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # allow pushing back to repo
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pytrends

      - name: Generate daily post
        run: python scripts/generate_post.py

      - name: Commit and push changes
        run: |
          git config user.name "Faceless AI Bot"
          git config user.email "bot@faceless-ai.site"
          git add -A
          git commit -m "Auto: daily post" || echo "No changes to commit"
          git push
